### ISSUE TITLE
Still problems with erased data after update

### ISSUE THREAD

**Issue by CaparsoX** [IngmarStein/Kraftstoff#2]
I also commented on the closed issue a few weeks ago but as I'm not sure if anyone's still reading it I'm opening a new thread.

My data was also back with the update to 1.2.3 but then I updated to iOS 9 and enabled iCloud Drive and now it's lost again. Don't know whether it's related to iOS 9 or iCloud Drive as I haven't used the app after updating to iOS 9 and before enabling iCloud Drive.

I used iBackup Viewer to look for the data and found several sqlite-files. This seems somewhat similar to what trumpar posted back on Sep. 7.

com.github.m-schmidt.kraftstoff\Documents\Kraftstoffrechner.sqlite.migrated
com.github.m-schmidt.kraftstoff\Documents\Kraftstoffrechner.sqlite-shm
com.github.m-schmidt.kraftstoff\Documents\Kraftstoffrechner.sqlite-wal (This seems to be the one with all my data as it's 194 KB and all other files are only between 32 and 64 KB. After opening the file with Notepad I also found a reference about my car and the license plate I entered when creating it.)

com.github.m-schmidt.kraftstoff\Documents\CoreDataUbiquitySupport\mobile~[ID1]\Kraftstoff2[IDx]\store\Fuel.sqlite
com.github.m-schmidt.kraftstoff\Documents\CoreDataUbiquitySupport\mobile~[ID1]\Kraftstoff2[IDy]\store\Fuel.sqlite (Also includes a reference about my car.)
com.github.m-schmidt.kraftstoff\Documents\CoreDataUbiquitySupport\mobile~[ID1]\Kraftstoff2\local\store\Fuel.sqlite

com.github.m-schmidt.kraftstoff\Documents\CoreDataUbiquitySupport\mobile~[ID2]\Kraftstoff\local\store\Fuel.sqlite.migrated (Also includes a reference about my car.)

Is there a way to fix this? Is it possible to export the sqlite-data and import it in the app? Or can you fix it with another app update? Really appreciate your help.

**Comment by IngmarStein** [comment]
Good news first: your data is not erased, it's still stored on iCloud (as you found out yourself).

Something seems to be really wrong with iCloud syncing. You might see some data when deleting the app from your device and reinstalling it, but syncing after that seems broken.
I'm on it, but I haven't really found the root cause, yet.

**Comment by IngmarStein** [comment]
You you have more than one iOS device? Have you launched the newest version on all of them?

**Comment by CaparsoX** [comment]
No, I only have one iOS device. I have the current iOS version on it (9.1) as well as the current version of the Kraftstoff app (1.3.1).

**Comment by IngmarStein** [comment]
Have you waited for a couple of minutes after starting the app? There is currently no visual feedback during the initial iCloud import and that may seem as if the data was lost.

**Comment by CaparsoX** [comment]
Yes, I've tried that now but nothing happened.
