### ISSUE TITLE
change lang

### ISSUE THREAD

**Issue by moh1122** [IngmarStein/Kraftstoff#3]
Hey thanks for this great app
is amazing
btw how can i change the lang u r saying u added french but how can the user change it?
Thank you

**Comment by IngmarStein** [comment]
Kraftstoff just uses the system settings. If your iPhone is set to French, that language will be used in the app.

**Comment by moh1122** [comment]
thnks u man
im testing the app on iphone 6 when i go into the graph mode the app crashes?

**Comment by IngmarStein** [comment]
I can't reproduce the issue. Do you have a crashlog for me or a CSV export of the data?

**Comment by IngmarStein** [comment]
Closed due to lack of feedback. Please reopen if you need more help.
